[package]
name = "giftaku_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#graphul = { version = "1.0.1"}
rocket = { version = "0.5.0-rc.3", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
surrealdb = "1.0.0"