[default]
address = "0.0.0.0"
port = 8000
temp_dir = "./upload"
cli_colors = true

[default.limits]
form = "20 MiB"
data-form = "20 MiB"
json = "20 MiB"
msgpack = "20 MiB"
"file/jpg" = "20 MiB"
"file/gif" = "20 MiB"

[default.shutdown]
ctrlc = true
signals = ["term", "hup"]
grace = 5
mercy = 5