[default]
address = "127.0.0.1"
port = 8000
temp_dir = "./upload"
cli_colors = true

[default.limits]
form = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"
"file/gif" = "5 MiB"

[default.shutdown]
ctrlc = true
signals = ["term", "hup"]
grace = 5
mercy = 5